"""baseline_schema

Revision ID: 2839843a822d
Revises: 
Create Date: 2026-07-06 20:14:21.849349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2839843a822d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sap_number', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('routing_time_minutes', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sap_number')
    )
    op.create_index('idx_products_sap', 'products', ['sap_number'], unique=False)
    op.create_table('technicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule')
    )
    op.create_index('idx_technicians_matricule', 'technicians', ['matricule'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('production_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('erp_order_id', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('erp_order_id', 'order_date', name='uq_erp_order_date')
    )
    op.create_index('idx_prod_orders_date', 'production_orders', ['order_date'], unique=False)
    op.create_index('idx_prod_orders_product', 'production_orders', ['product_id'], unique=False)
    op.create_table('schedule_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_date', sa.Date(), nullable=False),
    sa.Column('locked_by', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_date')
    )
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('is_working', sa.Boolean(), nullable=False),
    sa.Column('is_transferred', sa.Boolean(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('extra_time_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technician_id', 'shift_date', name='uq_tech_shift_date')
    )
    op.create_index('idx_shifts_date', 'shifts', ['shift_date'], unique=False)
    op.create_table('technician_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('skill_level', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technician_id', 'skill_level', name='uq_tech_skill_level')
    )
    op.create_index('idx_tech_skills_tech_id', 'technician_skills', ['technician_id'], unique=False)
    op.create_table('schedule_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_row_id', sa.UUID(), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('schedule_date', sa.Date(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('routing_time_minutes', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('remaining_time_minutes', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('is_expertise_override', sa.Boolean(), nullable=False),
    sa.Column('was_unblocked_by_manager', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('Planned', 'In Progress', 'Partially Completed', 'Completed', 'Blocked')", name='ck_assignment_status'),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_order_id', 'schedule_date', name='uq_order_assignment_date'),
    sa.UniqueConstraint('schedule_row_id')
    )
    op.create_index('idx_assignments_date', 'schedule_assignments', ['schedule_date'], unique=False)
    op.create_index('idx_assignments_status', 'schedule_assignments', ['status'], unique=False)
    op.create_index('idx_assignments_technician', 'schedule_assignments', ['technician_id', 'schedule_date'], unique=False)
    op.create_table('work_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('stopped_at IS NULL OR stopped_at > started_at', name='ck_session_time_order'),
    sa.ForeignKeyConstraint(['assignment_id'], ['schedule_assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_work_sessions_assignment', 'work_sessions', ['assignment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_work_sessions_assignment', table_name='work_sessions')
    op.drop_table('work_sessions')
    op.drop_index('idx_assignments_technician', table_name='schedule_assignments')
    op.drop_index('idx_assignments_status', table_name='schedule_assignments')
    op.drop_index('idx_assignments_date', table_name='schedule_assignments')
    op.drop_table('schedule_assignments')
    op.drop_index('idx_tech_skills_tech_id', table_name='technician_skills')
    op.drop_table('technician_skills')
    op.drop_index('idx_shifts_date', table_name='shifts')
    op.drop_table('shifts')
    op.drop_table('schedule_locks')
    op.drop_index('idx_prod_orders_product', table_name='production_orders')
    op.drop_index('idx_prod_orders_date', table_name='production_orders')
    op.drop_table('production_orders')
    op.drop_table('users')
    op.drop_index('idx_technicians_matricule', table_name='technicians')
    op.drop_table('technicians')
    op.drop_index('idx_products_sap', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
